namespace PylonRecon.IO;

public class PlyDocumentWriter : IPointCloudDocumentWriter
{
    public void WriteTo(PointCloud pointCloud, string filePath)
    {
        List<string> comments = new List<string>()
        {
            $"generated by PylonRecon.NET"
        };
        
        var stream = File.OpenWrite(filePath);
        StreamWriter writer = new(stream);
        writer.WriteLine("ply");
        writer.WriteLine("format ascii 1.0");
        foreach (var comment in comments)
        {
            writer.WriteLine($"comment {comment}");
        }
        writer.WriteLine($"element vertex {pointCloud.Count}");
        writer.WriteLine("property float x");
        writer.WriteLine("property float y");
        writer.WriteLine("property float z");
        writer.WriteLine("property float nx");
        writer.WriteLine("property float ny");
        writer.WriteLine("property float nz");
        writer.WriteLine("property uchar alpha");
        writer.WriteLine("property uchar red");
        writer.WriteLine("property uchar green");
        writer.WriteLine("property uchar blue");
        writer.WriteLine("end_header");
        foreach (var p in pointCloud)
        {
            writer.WriteLine($"{p.Location.X} {p.Location.Y} {p.Location.Z} {p.Normal.X} {p.Normal.Y} {p.Normal.Z} {p.Color.A} {p.Color.R} {p.Color.G} {p.Color.B}");
        }
        writer.Close();
        stream.Close();
    }
}